# -*- coding: utf-8 -*-
"""TugasBesarVisDat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nT1u3LNmQ2oIV10kglOqDTN6BpKpn9WB

# **Tugas Besar Visualisasi Data**
Fluktuasi Harga Saham
---

<b>Kelompok<b>:
*   Nur Latifah Kurnianti 1301194253
*   Revelin Anger S 1301194045
*   Arvia Dwi Cahyani 1301194151

<b> Kelas<b> : IF-42-GAB04

# Import Library dan Dataset
"""

import pandas as pd
import numpy as np
from google.colab import drive
from bokeh.io import output_file, output_notebook
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.layouts import row, column, gridplot
from bokeh.models.widgets import Tabs, Panel
from bokeh.core.validation import silence
from bokeh.core.validation.warnings import EMPTY_LAYOUT, MISSING_RENDERERS

"""Data set yang digunakan pada tugas besar 2 ini adalah data time series dari beberapa parameter saham yang terdiri dari:

•	Date: Tanggal pengambilan data

•	Adj Close: Harga penutupan yang telah disesuaikan

•	Volume: Jumlah transaksi

•	Open: Harga awal

•	High: Harga tertinggi

•	Low: Harga terendah

•	Close: harga akhir

•	Nama: Indeks pasar saham
"""

# Read File
!gdown --id 1tB88ycYizcUOjH6XJW4BO6WAD8icTPsl
df_saham = pd.read_excel("DATASAHAM.xlsx")
df_saham.head()

"""## Bagian 1
1.   Default Toolbar
2.   Hover
Teks yang muncul pada saat hover/kursor diletakkan di atas titik data yaitu: nama indeks pasar saham, dan nilai parameter.<br>
"""

# Memasukan hasil kedalam Notebook
output_notebook()

# Memisahkan data BMRI, BBRI, dan BBCA
BMRI = df_saham.loc[df_saham['Nama'] == 'BMRI']
BBRI = df_saham.loc[df_saham['Nama'] == 'BBRI']
BBCA = df_saham.loc[df_saham['Nama'] == 'BBCA']

saham_BMRI = dict(
    Date = BMRI['Date'].values,
    Open = BMRI['Open'].values.tolist(),
    High = BMRI['High'].values.tolist(),
    Low = BMRI['Low'].values.tolist(),
    Close = BMRI['Close'].values.tolist(),
    Adj_Close = BMRI['Adj Close'].values.tolist(),
    Volume = BMRI['Volume'].values.tolist(),
    Nama = BMRI['Nama'].values.tolist()
)
saham_BBRI = dict(
    Date = BBRI['Date'].values,
    Open = BBRI['Open'].values.tolist(),
    High = BBRI['High'].values.tolist(),
    Low = BBRI['Low'].values.tolist(),
    Close = BBRI['Close'].values.tolist(),
    Adj_Close = BBRI['Adj Close'].values.tolist(),
    Volume = BBRI['Volume'].values.tolist(),
    Nama = BBRI['Nama'].values.tolist()
)
saham_BBCA = dict(
    Date = BBCA['Date'].values,
    Open = BBCA['Open'].values.tolist(),
    High = BBCA['High'].values.tolist(),
    Low = BBCA['Low'].values.tolist(),
    Close = BBCA['Close'].values.tolist(),
    Adj_Close = BBCA['Adj Close'].values.tolist(),
    Volume = BBCA['Volume'].values.tolist(),
    Nama = BBCA['Nama'].values.tolist()
)

# Membuat object CloumDataSearch pada setiap saham
BMRI_data = ColumnDataSource(dict_BMRI)
BBRI_data = ColumnDataSource(dict_BBRI)
BBCA_data = ColumnDataSource(dict_BBCA)

# Konfigurasi saham
nilai = figure(x_axis_type='datetime',
             plot_height=600, plot_width=900,
             title='Nilai Adj Close setiap Indeks Saham',
             x_axis_label='Date', y_axis_label='Adj Close')

# Memvisualisasikan nilai 2 dan nilai 3
nilai.line('Date', 'Adj_Close', color='red', legend_label='BMRI',source=BMRI_data)
nilai.line('Date', 'Adj_Close', color='navy', legend_label='BBRI', source=BBRI_data)
nilai.line('Date', 'Adj_Close', color='green', legend_label='BBCA', source=BBCA_data)

nilai.legend.location = 'top_right'

# Format tooltip pada Hover
tools = HoverTool(tooltips=[('Index', '@Nama'), ('Date', '@Date{%F}'),
                            ('Close', '$@Adj_Close{%0.2f}'),],
                 formatters={'@Date': 'datetime', '@Adj_Close': 'printf'}
                  )

# Menambahkan nilai pada HoverTool
nilai.add_tools(tools)

"""##Bagian 2 

Menambah aspek interaktif yang memungkinkan user memilih parameter yang akan ditampilkan:

Adj Close dan Volume

Nilai parameter yang muncul pada hover tool harus disesuaikan dengan parameter yang dipilih.
"""

# Konfigurasi nilai 2 dan nilai 3
nilai2 = figure(x_axis_type='datetime',
             plot_height=600, plot_width=900,
             title='Nilai Volume setiap Indeks Saham',
             x_axis_label='Date', y_axis_label='Volume')

nilai3 = figure(x_axis_type='datetime',
             plot_height=600, plot_width=900,
             title='Nilai Adj Close Indeks Saham',
             x_axis_label='Date', y_axis_label='Adj Close')

# Memvisualiasasikan nilai 2 dan nilai 3
nilai2.line('Date', 'Volume', color='red', legend_label='BMRI', source=BMRI_data)
nilai2.line('Date', 'Volume', color='navy', legend_label='BBRI', source=BBRI_data)
nilai2.line('Date', 'Volume', color='green', legend_label='BBCA', source=BBCA_data)

nilai3.line('Date', 'Adj Close', color='red', legend_label='BMRI', source=BMRI_data)
nilai3.line('Date', 'Adj Close', color='navy', legend_label='BBRI', source=BBRI_data)
nilai3.line('Date', 'Adj Close', color='green', legend_label='BBCA', source=BBCA_data)

nilai.legend.location = 'top_right'

# Format tooltip pada Hover
tools1 = HoverTool(
  tooltips=[('Index', '@Nama'),('Date', '@Date{%F}'),('Volume', '@Volume{%0.2f}'),],
  formatters={'@Date': 'datetime','@Volume': 'printf'}
)

tools2 = HoverTool(
  tooltips=[('Index', '@Nama'),('Date', '@Date{%F}'),('Adj Close', '@Adj_Close{%0.2f}'),],
  formatters={'@Date': 'datetime','@Adj_Close': 'printf'}
)

# Memasukkan HoverTool ke nilai2
nilai2.add_tools(tools1)
nilai3.add_tools(tools2)

# Membuat 3 panel, yang salah satunya memiliki parameter
adj_panel = Panel(child=nilai, title='Adj Close')
vol_panel = Panel(child=nilai2, title='Volume')

# Menetapkan panel pada Tabs
tabs = Tabs(tabs=[adj_panel, vol_panel])

# Menampilkan layout Tabs
show(tabs)

"""##Bagian 3

Menambahkan aspek interaktif yang digunakan untuk menyembunyikan data untuk indeks pasar saham tertentu .
"""

# Menyembunyikan data untuk indeks pasar saham tertentu
nilai.legend.click_policy="hide"
nilai2.legend.click_policy="hide"
nilai3.legend.click_policy="hide"

# Menampilkan layout Tabs
show(tabs)